### ISSUE TITLE
Request: Also publish to open-vsx.org

### ISSUE THREAD

**Issue by aidalgol** [Kode/vscode-kha-extension-pack#4]
Could this please also be published to the [open-vsx.org](https://open-vsx.org/) extension gallery?  This would make it easier to install in [VSCodium](https://vscodium.com/) (the free/libre build of VSCode).  Instructions on how to do this are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by RobDangerous** [comment]
I'm sorry but I don't even know how to fill out their weird publishing agreement. They want to know my employment status but my employer doesn't have anything to do with these projects. Until this eclipse stuff becomes less crazy it's sadly a no-go.
